checkout:
  post:
    - git submodule sync
    - git submodule update --init --recursive
dependencies:
  override:
    - meteor
test:
  override:
    - tests/test-runner/test-all.sh
jobs:
  build:
    machine:
      node:
        version: 0.10.33
      pre:
        - curl https://install.meteor.com | /bin/sh
    steps:
      - run: meteor build
