checkout:
  post:
    - git submodule sync
    - git submodule update --init --recursive
machine:
  node:
    version: 0.10.33
  pre:
    - curl https://install.meteor.com | /bin/sh
dependencies:
  override:
    - npm install selenium-webdriver@2.47.0 mkdirp
    - meteor list
test:
  override:
    - tests/test-runner/test-all.sh
