checkout:
  post:
    - git submodule sync
    - git submodule update --init --recursive
machine:
  node:
    version: 0.10.33
  pre:
    - curl https://install.meteor.com | /bin/sh
dependencies:
  override:
    - meteor
test:
  override:
    - tests/test-runner/test-all.sh
jobs:
  build:
    - meteor build
